
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

// SQLite relative paths in DATABASE_URL are resolved relative to schema.prisma
// by the CLI but relative to process.cwd() by the generated Client at runtime.
// Using an absolute path here keeps the CLI pointed at the same file
// (<project root>/prisma/dev.db) that the app opens via DATABASE_URL in .env.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: `file:${path.join(process.cwd(), "prisma", "dev.db")}`,
  },
});
